name: Cordova APK Derleme

on:
  push:
    branches: [ "ana" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Kontrol Et
        uses: actions/checkout@v4

      - name: JDK 11 Kurulumu
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Node.js Kurulumu
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cordova Bağımlılıklarını Yükle
        run: |
          npm install -g cordova
          cordova platform add android

      - name: APK Derleme
        run: cordova build android --release

      - name: APK'yı Yükle
        uses: actions/upload-artifact@v4
        with:
          name: kutu-kapat-apk
          path: platforms/android/app/build/outputs/apk/release/app-release.apk
